import { Company, User, Policy, FloorMapZone, EscalationLog } from './types';

export const INITIAL_COMPANIES: Company[] = [
  {
    id: "acme",
    name: "Acme Corp",
    domain: "acmecorp.com",
    joinCode: "ACME-2026",
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: "u1",
    companyId: "acme",
    name: "Claire Admin",
    email: "claire.admin@acmecorp.com",
    role: "HR_Admin",
    accountType: "Company_Account",
    status: "Active",
    joinedAt: "2024-01-15",
  },
  {
    id: "u2",
    companyId: "acme",
    name: "Alex Test",
    email: "alex.test@gmail.com",
    role: "Employee",
    accountType: "Personal_Account",
    status: "Pending_Approval",
    joinedAt: "2026-09-06",
  },
  {
    id: "u3",
    companyId: "acme",
    name: "James Wilson",
    email: "james.wilson@acmecorp.com",
    role: "Employee",
    accountType: "Company_Account",
    status: "Active",
    joinedAt: "2025-03-10",
  },
  {
    id: "u4",
    companyId: "acme",
    name: "Juan Dela Cruz",
    email: "juan@acmecorp.com",
    role: "Employee",
    accountType: "Company_Account",
    status: "Active",
    joinedAt: "2025-06-01",
  },
];

export const INITIAL_POLICIES: Policy[] = [
  {
    id: "p1",
    companyId: "acme",
    title: "2026_PTO_Policy.pdf",
    content: "Acme Corp provides 15 days of paid time off (PTO) per calendar year, along with 5 days of bereavement leave. Up to 3 unused PTO days can roll over to the next year.",
    lastUpdated: "2026-01-05",
    category: "Leave & Attendance",
  },
  {
    id: "p2",
    companyId: "acme",
    title: "Remote_Work_Guide.pdf",
    content: "Under our Remote Work Policy, Acme Corp provides a $50/month internet reimbursement and a one-time $300 home office equipment stipend.",
    lastUpdated: "2026-02-14",
    category: "Workplace & Equipment",
  },
  {
    id: "p3",
    companyId: "acme",
    title: "Health_Benefits_2026.pdf",
    content: "Annual open enrollment runs from November 1 to November 30. Comprehensive medical, dental, and vision coverage details are available in the benefits portal, with up to a $500 employer HSA match.",
    lastUpdated: "2026-03-01",
    category: "Healthcare & Perks",
  },
  {
    id: "p4",
    companyId: "acme",
    title: "Workplace_Conduct_2026.pdf",
    content: "Under Acme Corp's Workplace Conduct Policy, employees are guaranteed an inclusive environment free from harassment and discrimination, with equal opportunity for advancement. Concerns can be confidentially reported to ethics@acmecorp.com or via the HR Portal with strict non-retaliation protections.",
    lastUpdated: "2026-01-10",
    category: "Compliance & Workplace Ethics",
  },
  {
    id: "p5",
    companyId: "acme",
    title: "IT_Security_Policy.pdf",
    content: "Under our IT Security Policy, all employees must enable Multi-Factor Authentication (MFA), utilize company hardware eligible for a 3-year laptop refresh cycle, and report lost or stolen devices within 2 hours to security@acmecorp.com.",
    lastUpdated: "2026-02-01",
    category: "IT & Information Security",
  },
  {
    id: "p_dole_exec",
    companyId: "acme",
    title: "DOLE_Executive_Mandate.pdf",
    content: "DOLE Executive Mandate & Overview (dole.gov.ph)\n\nThe Department of Labor and Employment (DOLE) is the primary executive agency of the Philippine Government mandated to formulate, coordinate, and implement policies and programs in labor and employment.\n\nCore Pillars:\n1. Gainful Employment Promotion: Local and overseas employment facilitation, career guidance, and skills development programs.\n2. Worker Protection & Welfare: Enforcing statutory minimum wages, workplace health and occupational safety standards, and social protection programs.\n3. Industrial Peace: Resolving labor-management disputes through conciliation-mediation (Single Entry Approach / SEnA) and voluntary arbitration.",
    lastUpdated: "2026-03-01",
    category: "DOLE & Philippine Labor Law",
  },
  {
    id: "p_dole_book3",
    companyId: "acme",
    title: "DOLE_Labor_Code_Book3.pdf",
    content: "Labor Code Book 3: Conditions of Employment (dole.gov.ph/book-3-conditions-of-employment/)\n\nCoverage (Art. 82): Applies to all employees in all establishments, whether operating for profit or not. Exemptions: Government employees, managerial staff, field personnel, family dependents of the employer, and domestic workers.\n\nHours of Work & Meals (Arts. 83–85):\n- Maximum 8 normal working hours per day.\n- Mandatory minimum 60-minute uncompensated meal period. Short rest periods (5–20 minutes) during working hours are compensable working time.\n\nNight Shift Differential (Art. 86):\n- Plus 10% of regular hourly wage for work performed between 10:00 PM and 6:00 AM.\n\nOvertime Pay (Arts. 87–88):\n- Regular Workday OT: Plus 25% of the regular hourly rate for work performed beyond 8 hours.\n- Rest Day or Holiday OT: Plus 30% of the rest day or holiday hourly rate.\n- Undertime Rule: Undertime on any regular workday cannot be offset by overtime work performed on any other day.\n\nWeekly Rest Day (Arts. 91–93):\n- Right to 24 consecutive hours of rest after every 6 consecutive normal workdays.\n- Work on scheduled rest day commands a 30% premium pay (+50% if the rest day coincides with a special holiday).\n\nHolidays & Service Incentive Leave (Arts. 94–95):\n- Regular Holidays: Paid 100% of regular daily wage if unworked; paid 200% for the first 8 hours if worked.\n- Special Non-Working Days: Follows 'no work, no pay'; paid 130% of regular wage if worked.\n- Service Incentive Leave (SIL): 5 days of paid annual leave for every employee who has rendered at least 1 year of service; commutable to cash if unused at year end.\n\nService Charges (Art. 96 & R.A. 11360):\n- 100% of service charges collected by hotels, restaurants, and similar establishments must be distributed equally among covered rank-and-file and supervisory employees.\n\nWages & Deductions (Arts. 97–119):\n- Minimum wages are set regionally by Regional Tripartite Wages and Productivity Boards (RTWPB).\n- Wages must be paid at least twice monthly at intervals not exceeding 16 days.\n- Unauthorized wage deductions are strictly prohibited, except for statutory contributions (SSS, PhilHealth, Pag-IBIG), withholding taxes, or employee-authorized union check-offs.",
    lastUpdated: "2026-03-01",
    category: "Labor Standards & Book 3",
  },
  {
    id: "p_dole_mandatory",
    companyId: "acme",
    title: "DOLE_Mandatory_Policies_2026.pdf",
    content: "DOLE Mandatory Workplace Policies & Programs (laborlaw.ph/mandatory-workplace-policies-and-programs/)\n\n1. Occupational Safety & Health (OSH) Program:\n- Mandated under R.A. 11058 and DOLE DO 198-18.\n- Requires appointment of certified Safety Officers, certified First Aiders, an active Health & Safety Committee, and mandatory 8-hour safety orientation for all workers.\n\n2. Drug-Free Workplace Policy:\n- Mandated under R.A. 9165 and DOLE DO 53-03.\n- Requires annual drug education orientations, random drug testing protocols by DOH-accredited centers, and confidential rehabilitation assistance.\n\n3. Anti-Sexual Harassment & Safe Spaces Act:\n- Mandated under R.A. 7877 and R.A. 11313 (Safe Spaces Act).\n- Requires zero tolerance for sexual harassment and gender-based harassment. Mandates an established Committee on Decorum and Investigation (CODI) to investigate and resolve grievances within 10 days.\n\n4. Mental Health Workplace Policy:\n- Mandated under R.A. 11036 and DOLE DO 208-20.\n- Requires workplace mental health education, stigma reduction, psychological support services, and clear counseling referral pathways.\n\n5. Health Disease Control Programs:\n- HIV/AIDS Workplace Policy (R.A. 11166 / DO 102-10), Tuberculosis Control (DO 73-05), Hepatitis B (DA 05-10).\n- Enforces medical record confidentiality, strict non-discrimination, and guaranteed job restoration upon medical clearance.\n\n6. Family Welfare & Lactation Facilities:\n- Lactation Stations mandated under R.A. 10028 with clean facilities and compensable nursing breaks of at least 40 minutes per 8-hour shift.\n- Family Welfare Program (DO 56-03) covering 10 health and welfare dimensions.",
    lastUpdated: "2026-03-01",
    category: "DOLE Mandatory Programs",
  },
];

export const INITIAL_FLOOR_ZONES: FloorMapZone[] = [
  {
    id: "f1",
    companyId: "acme",
    name: "HR Helpdesk (Zone 2B)",
    capacity: "4 desks",
    category: "HR Desk",
    description: "In-person HR support, onboarding badge collection, and confidential benefits consultations.",
    x: 62,
    y: 28,
    width: 28,
    height: 28,
    color: "#4f46e5",
    statusText: "🟢 Open | Wait Time: < 5 mins",
    statusType: "open",
    waitTime: "< 5 mins",
    attendant: "Claire Admin",
  },
  {
    id: "f2",
    companyId: "acme",
    name: "Executive Boardroom",
    capacity: "12 people",
    category: "Meeting Room",
    description: "4K telepresence display, acoustic soundproofing, dual whiteboard array.",
    x: 10,
    y: 15,
    width: 38,
    height: 30,
    color: "#0284c7",
    statusText: "🔴 In Use until 3:30 PM | Capacity: 12",
    statusType: "busy",
    waitTime: "In use until 3:30 PM",
    attendant: "Operations Desk",
  },
  {
    id: "f3",
    companyId: "acme",
    name: "Engineering Pod Alpha",
    capacity: "16 desks",
    category: "Workspace",
    description: "Standing motorized desks, dual-monitor mounts, team scrum huddle area.",
    x: 10,
    y: 52,
    width: 48,
    height: 38,
    color: "#059669",
    statusText: "🟢 Open Workstations Available",
    statusType: "open",
    waitTime: "Available",
    attendant: "IT Tech Bar",
  },
  {
    id: "f4",
    companyId: "acme",
    name: "Acme Bistro & Town Hall Lounge",
    capacity: "30 people",
    category: "Common Area",
    description: "Cold brew tap, espresso machine, organic snacks, open amphitheater seating.",
    x: 62,
    y: 60,
    width: 30,
    height: 30,
    color: "#d97706",
    statusText: "🟡 Moderate Crowd (45% capacity) | Open",
    statusType: "moderate",
    waitTime: "No wait",
    attendant: "Hospitality Lead",
  },
];

export const INITIAL_ESCALATION_LOGS: EscalationLog[] = [
  {
    id: "e1",
    companyId: "acme",
    userEmail: "james.wilson@acmecorp.com",
    question: "Can we get paid in Bitcoin?",
    status: "Pending",
    hrResponse: "",
    respondedBy: "",
    respondedAt: "",
    createdAt: "2026-09-06 14:22",
    threadId: "chat-bitcoin",
  },
  {
    id: "e2",
    companyId: "acme",
    userEmail: "alex.test@gmail.com",
    question: "Do we offer pet insurance coverage?",
    status: "Resolved",
    hrResponse: "Hi Alex! We offer 15% group rates via Nationwide. Check portal for links.",
    respondedBy: "Claire Admin",
    respondedAt: "2026-09-07",
    createdAt: "2026-09-05 09:15",
    threadId: "chat-pet-insurance",
  },
];
